wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1630925241
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.10
      5: 0.12.1
      8:
      - 3
      - 5
gamma:
  desc: null
  value: 0.99
mu_lr:
  desc: null
  value: 0.0005
q_lr:
  desc: null
  value: 0.001
tau:
  desc: null
  value: 0.005
